version: "3.8"
services:
  python:
    container_name: BBC-Scraper-Service
    build: .
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        python main.py